name: Deploy naar GitHub Pages

# Trigger bij push naar main
on:
  push:
    branches:
      - main

# Geef expliciet de juiste permissies
permissions:
  contents: read       # lees-toegang voor de repo-inhoud
  pages: write         # schrijf-toegang voor GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy naar gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # hiermee gebruikt hij automatisch ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
